name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image from DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: sudo docker pull $DOCKER_USERNAME/cicd-test:latest
    
    - name: Delete old Docker Container
      run: sudo docker rm -f cicd-test-container || true
      
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-test-container ${{ secrets.DOCKER_USERNAME}}/cicd-test
