name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest -t ${{ secrets.DOCKER_USERNAME }}/cicd-test:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-test:$IMAGE_TAG
